### ISSUE TITLE
Log file name

### ISSUE THREAD

**Issue by ghispi** [scheb/tombstone-analyzer#9]
scheb/tombstone: 0.19.0
scheb/tombstone-analyzer: 0.6.0

There seem to be discrepancy between what https://github.com/scheb/tombstone README.md suggests and what files are used by analyzer.

In thombstone readme we have:
https://github.com/scheb/tombstone/blob/bb7c7750a5c8af6cee61622a7757f83fb4c9b92b/README.md#L54
```php
 $streamHandler = new StreamHandler("$logDir/tombstones.log");
```
yet
https://github.com/scheb/tombstone-analyzer/blob/befda020d15c490e54edd4331c49d45aaa063ba0/src/Log/AnalyzerLogDirectoryReader.php#L42
explicitly looks for *.tombstone.

I think it should be configurable in analyzer.

**Comment by ghispi** [comment]
Sorry, I did not read the documentation fully. This is not an issue.
Although it may be worth to make the Installation step use initialization that is compatible with analyzer.

**Comment by scheb** [comment]
I extended documentation to explicitly mention the `AnalyzerLogHandler` to avoid this confusion in the future.
